CODING_QUESTION_BANK: dict[str, list[dict]] = {
    "Data Scientist": [
        {
            "id": "ds_code_01",
            "type": "coding",
            "sub_topic": "Data Cleaning",
            "text": "Write a function that returns the sum of all values except missing values represented by -1.",
            "function_name": "remove_missing_and_sum",
            "param_types": ["int[]"],
            "return_type": "int",
            "starter_code": {
                "python": "def remove_missing_and_sum(values):\n    total = 0\n    for value in values:\n        # skip missing values represented by -1\n        pass\n    return total\n",
                "java": "public class Solution {\n    public static int remove_missing_and_sum(int[] values) {\n        int total = 0;\n        for (int value : values) {\n            // skip missing values represented by -1\n        }\n        return total;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[4, -1, 3, 7]], "expected": 14},
                {"input": [[-1, -1, 5]], "expected": 5},
                {"input": [[2, 2, 2]], "expected": 6},
            ],
        },
        {
            "id": "ds_code_02",
            "type": "coding",
            "sub_topic": "Thresholding",
            "text": "Write a function that counts how many scores are strictly greater than the given threshold.",
            "function_name": "count_above_threshold",
            "param_types": ["int[]", "int"],
            "return_type": "int",
            "starter_code": {
                "python": "def count_above_threshold(scores, threshold):\n    count = 0\n    for score in scores:\n        # increment count when score is above threshold\n        pass\n    return count\n",
                "java": "public class Solution {\n    public static int count_above_threshold(int[] scores, int threshold) {\n        int count = 0;\n        for (int score : scores) {\n            // increment count when score is above threshold\n        }\n        return count;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[45, 81, 63, 91], 70], "expected": 2},
                {"input": [[10, 20, 30], 30], "expected": 0},
                {"input": [[88, 89, 90], 80], "expected": 3},
            ],
        },
        {
            "id": "ds_code_03",
            "type": "coding",
            "sub_topic": "Trend Analysis",
            "text": "Write a function that returns the length of the longest non-decreasing streak in the array.",
            "function_name": "longest_non_decreasing_streak",
            "param_types": ["int[]"],
            "return_type": "int",
            "starter_code": {
                "python": "def longest_non_decreasing_streak(values):\n    if not values:\n        return 0\n    best = 1\n    current = 1\n    # update the longest non-decreasing streak\n    return best\n",
                "java": "public class Solution {\n    public static int longest_non_decreasing_streak(int[] values) {\n        if (values.length == 0) {\n            return 0;\n        }\n        int best = 1;\n        int current = 1;\n        // update the longest non-decreasing streak\n        return best;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[1, 2, 2, 1, 3, 4]], "expected": 3},
                {"input": [[5, 5, 5]], "expected": 3},
                {"input": [[9, 7, 5]], "expected": 1},
            ],
        },
    ],
    "AI/ML Engineer": [
        {
            "id": "ml_code_01",
            "type": "coding",
            "sub_topic": "Inference",
            "text": "Write a function that converts scores into binary predictions using the threshold. Return 1 when score >= threshold, else 0.",
            "function_name": "binary_predictions",
            "param_types": ["int[]", "int"],
            "return_type": "int[]",
            "starter_code": {
                "python": "def binary_predictions(scores, threshold):\n    result = []\n    for score in scores:\n        # append 1 or 0 based on the threshold\n        pass\n    return result\n",
                "java": "import java.util.*;\npublic class Solution {\n    public static int[] binary_predictions(int[] scores, int threshold) {\n        int[] result = new int[scores.length];\n        for (int i = 0; i < scores.length; i++) {\n            // fill result based on the threshold\n        }\n        return result;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[40, 70, 55, 90], 60], "expected": [0, 1, 0, 1]},
                {"input": [[60, 60], 60], "expected": [1, 1]},
                {"input": [[10, 20], 30], "expected": [0, 0]},
            ],
        },
        {
            "id": "ml_code_02",
            "type": "coding",
            "sub_topic": "Evaluation",
            "text": "Write a function that counts how many predictions exactly match the labels.",
            "function_name": "count_correct_predictions",
            "param_types": ["int[]", "int[]"],
            "return_type": "int",
            "starter_code": {
                "python": "def count_correct_predictions(predictions, labels):\n    count = 0\n    for index in range(len(predictions)):\n        # compare prediction and label at the same index\n        pass\n    return count\n",
                "java": "public class Solution {\n    public static int count_correct_predictions(int[] predictions, int[] labels) {\n        int count = 0;\n        for (int i = 0; i < predictions.length; i++) {\n            // compare prediction and label at the same index\n        }\n        return count;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[1, 0, 1], [1, 1, 1]], "expected": 2},
                {"input": [[0, 0], [0, 0]], "expected": 2},
                {"input": [[1, 1, 1], [0, 0, 0]], "expected": 0},
            ],
        },
        {
            "id": "ml_code_03",
            "type": "coding",
            "sub_topic": "Learning Rate Scheduling",
            "text": "Write a function that applies integer decay steps to a learning rate value. Subtract decay each step but never go below 1.",
            "function_name": "decay_learning_rate",
            "param_types": ["int", "int", "int"],
            "return_type": "int",
            "starter_code": {
                "python": "def decay_learning_rate(rate, decay, steps):\n    current = rate\n    # apply decay for the given number of steps\n    return current\n",
                "java": "public class Solution {\n    public static int decay_learning_rate(int rate, int decay, int steps) {\n        int current = rate;\n        // apply decay for the given number of steps\n        return current;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [10, 2, 3], "expected": 4},
                {"input": [5, 3, 2], "expected": 1},
                {"input": [7, 1, 0], "expected": 7},
            ],
        },
    ],
    "Data Analyst": [
        {
            "id": "da_code_01",
            "type": "coding",
            "sub_topic": "Filtering",
            "text": "Write a function that returns only the even ids from the input array while preserving order.",
            "function_name": "filter_even_ids",
            "param_types": ["int[]"],
            "return_type": "int[]",
            "starter_code": {
                "python": "def filter_even_ids(ids):\n    result = []\n    for value in ids:\n        # keep only even ids\n        pass\n    return result\n",
                "java": "import java.util.*;\npublic class Solution {\n    public static int[] filter_even_ids(int[] ids) {\n        ArrayList<Integer> values = new ArrayList<>();\n        for (int value : ids) {\n            // keep only even ids\n        }\n        int[] result = new int[values.size()];\n        for (int i = 0; i < values.size(); i++) {\n            result[i] = values.get(i);\n        }\n        return result;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[1, 2, 3, 4, 6]], "expected": [2, 4, 6]},
                {"input": [[7, 9]], "expected": []},
                {"input": [[8, 10]], "expected": [8, 10]},
            ],
        },
        {
            "id": "da_code_02",
            "type": "coding",
            "sub_topic": "Counting",
            "text": "Write a function that counts how many department names match the target department.",
            "function_name": "count_department_occurrences",
            "param_types": ["String[]", "String"],
            "return_type": "int",
            "starter_code": {
                "python": "def count_department_occurrences(departments, target):\n    count = 0\n    for name in departments:\n        # increment count when the department matches target\n        pass\n    return count\n",
                "java": "public class Solution {\n    public static int count_department_occurrences(String[] departments, String target) {\n        int count = 0;\n        for (String name : departments) {\n            // increment count when the department matches target\n        }\n        return count;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [["finance", "sales", "finance"], "finance"], "expected": 2},
                {"input": [["ops", "ops"], "sales"], "expected": 0},
                {"input": [["hr"], "hr"], "expected": 1},
            ],
        },
        {
            "id": "da_code_03",
            "type": "coding",
            "sub_topic": "Ranking",
            "text": "Write a function that returns the maximum value in the array. Return 0 for an empty array.",
            "function_name": "max_value",
            "param_types": ["int[]"],
            "return_type": "int",
            "starter_code": {
                "python": "def max_value(values):\n    if not values:\n        return 0\n    best = values[0]\n    # update the maximum value\n    return best\n",
                "java": "public class Solution {\n    public static int max_value(int[] values) {\n        if (values.length == 0) {\n            return 0;\n        }\n        int best = values[0];\n        // update the maximum value\n        return best;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[10, 40, 25]], "expected": 40},
                {"input": [[]], "expected": 0},
                {"input": [[-5, -2, -8]], "expected": -2},
            ],
        },
    ],
    "Full Stack Developer": [
        {
            "id": "fs_code_01",
            "type": "coding",
            "sub_topic": "Routing",
            "text": "Write a function that joins a base path and numeric user id using a single slash.",
            "function_name": "build_user_path",
            "param_types": ["String", "int"],
            "return_type": "String",
            "starter_code": {
                "python": "def build_user_path(base, user_id):\n    # return a path like /users/42\n    return ''\n",
                "java": "public class Solution {\n    public static String build_user_path(String base, int user_id) {\n        // return a path like /users/42\n        return \"\";\n    }\n}\n",
            },
            "test_cases": [
                {"input": ["/users", 42], "expected": "/users/42"},
                {"input": ["api/profile", 7], "expected": "api/profile/7"},
                {"input": ["/account", 0], "expected": "/account/0"},
            ],
        },
        {
            "id": "fs_code_02",
            "type": "coding",
            "sub_topic": "Validation",
            "text": "Write a function that counts valid email strings. An email is valid when it contains both '@' and '.'.",
            "function_name": "count_valid_emails",
            "param_types": ["String[]"],
            "return_type": "int",
            "starter_code": {
                "python": "def count_valid_emails(emails):\n    count = 0\n    for email in emails:\n        # count only valid emails\n        pass\n    return count\n",
                "java": "public class Solution {\n    public static int count_valid_emails(String[] emails) {\n        int count = 0;\n        for (String email : emails) {\n            // count only valid emails\n        }\n        return count;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [["a@test.com", "broken", "x@y.org"]], "expected": 2},
                {"input": [["wrong.com", "stillwrong"]], "expected": 0},
                {"input": [["ok@site.dev"]], "expected": 1},
            ],
        },
        {
            "id": "fs_code_03",
            "type": "coding",
            "sub_topic": "HTTP Status",
            "text": "Write a function that maps HTTP status codes: 200 -> 'success', 404 -> 'not_found', anything else -> 'error'.",
            "function_name": "status_from_code",
            "param_types": ["int"],
            "return_type": "String",
            "starter_code": {
                "python": "def status_from_code(code):\n    # map 200, 404, and all other codes\n    return ''\n",
                "java": "public class Solution {\n    public static String status_from_code(int code) {\n        // map 200, 404, and all other codes\n        return \"\";\n    }\n}\n",
            },
            "test_cases": [
                {"input": [200], "expected": "success"},
                {"input": [404], "expected": "not_found"},
                {"input": [500], "expected": "error"},
            ],
        },
    ],
    "Software Engineer": [
        {
            "id": "se_code_01",
            "type": "coding",
            "sub_topic": "Arrays",
            "text": "Write a function that returns the index of target in a sorted array using binary search, or -1 if missing.",
            "function_name": "binary_search_index",
            "param_types": ["int[]", "int"],
            "return_type": "int",
            "starter_code": {
                "python": "def binary_search_index(nums, target):\n    left = 0\n    right = len(nums) - 1\n    while left <= right:\n        # implement binary search\n        pass\n    return -1\n",
                "java": "public class Solution {\n    public static int binary_search_index(int[] nums, int target) {\n        int left = 0;\n        int right = nums.length - 1;\n        while (left <= right) {\n            // implement binary search\n        }\n        return -1;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[1, 3, 5, 7], 5], "expected": 2},
                {"input": [[2, 4, 6], 1], "expected": -1},
                {"input": [[9], 9], "expected": 0},
            ],
        },
        {
            "id": "se_code_02",
            "type": "coding",
            "sub_topic": "Stacks",
            "text": "Write a function that returns true when the brackets in the string are balanced. Only (), {}, and [] are used.",
            "function_name": "is_balanced",
            "param_types": ["String"],
            "return_type": "boolean",
            "starter_code": {
                "python": "def is_balanced(s):\n    stack = []\n    pairs = {')': '(', ']': '[', '}': '{'}\n    # implement balanced bracket checking\n    return len(stack) == 0\n",
                "java": "import java.util.*;\npublic class Solution {\n    public static boolean is_balanced(String s) {\n        ArrayList<Character> stack = new ArrayList<>();\n        // implement balanced bracket checking\n        return stack.isEmpty();\n    }\n}\n",
            },
            "test_cases": [
                {"input": ["()[]{}"], "expected": True},
                {"input": ["(]"], "expected": False},
                {"input": ["{[()]}"], "expected": True},
            ],
        },
        {
            "id": "se_code_03",
            "type": "coding",
            "sub_topic": "Deduplication",
            "text": "Write a function that removes duplicates from a sorted array while preserving order.",
            "function_name": "deduplicate_sorted",
            "param_types": ["int[]"],
            "return_type": "int[]",
            "starter_code": {
                "python": "def deduplicate_sorted(nums):\n    result = []\n    # keep one copy of each value in sorted order\n    return result\n",
                "java": "import java.util.*;\npublic class Solution {\n    public static int[] deduplicate_sorted(int[] nums) {\n        ArrayList<Integer> result = new ArrayList<>();\n        // keep one copy of each value in sorted order\n        int[] output = new int[result.size()];\n        for (int i = 0; i < result.size(); i++) {\n            output[i] = result.get(i);\n        }\n        return output;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[1, 1, 2, 2, 3]], "expected": [1, 2, 3]},
                {"input": [[5, 5, 5]], "expected": [5]},
                {"input": [[]], "expected": []},
            ],
        },
    ],
    "DevOps Engineer": [
        {
            "id": "devops_code_01",
            "type": "coding",
            "sub_topic": "Health Checks",
            "text": "Write a function that counts how many service status strings are exactly 'healthy'.",
            "function_name": "count_healthy_services",
            "param_types": ["String[]"],
            "return_type": "int",
            "starter_code": {
                "python": "def count_healthy_services(statuses):\n    count = 0\n    for status in statuses:\n        # count healthy services\n        pass\n    return count\n",
                "java": "public class Solution {\n    public static int count_healthy_services(String[] statuses) {\n        int count = 0;\n        for (String status : statuses) {\n            // count healthy services\n        }\n        return count;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [["healthy", "down", "healthy"]], "expected": 2},
                {"input": [["down", "degraded"]], "expected": 0},
                {"input": [["healthy"]], "expected": 1},
            ],
        },
        {
            "id": "devops_code_02",
            "type": "coding",
            "sub_topic": "Retries",
            "text": "Write a function that returns true when any HTTP status code is 500 or greater, meaning a retry is needed.",
            "function_name": "retry_needed",
            "param_types": ["int[]"],
            "return_type": "boolean",
            "starter_code": {
                "python": "def retry_needed(status_codes):\n    for code in status_codes:\n        # return True if any status code needs a retry\n        pass\n    return False\n",
                "java": "public class Solution {\n    public static boolean retry_needed(int[] status_codes) {\n        for (int code : status_codes) {\n            // return true if any status code needs a retry\n        }\n        return false;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[200, 502, 204]], "expected": True},
                {"input": [[200, 201]], "expected": False},
                {"input": [[500]], "expected": True},
            ],
        },
        {
            "id": "devops_code_03",
            "type": "coding",
            "sub_topic": "Monitoring",
            "text": "Write a function that returns the maximum sum of any 3 consecutive CPU readings. If there are fewer than 3 readings, return the sum of all readings.",
            "function_name": "max_cpu_window",
            "param_types": ["int[]"],
            "return_type": "int",
            "starter_code": {
                "python": "def max_cpu_window(values):\n    # return the best sum for any window of size 3\n    return 0\n",
                "java": "public class Solution {\n    public static int max_cpu_window(int[] values) {\n        // return the best sum for any window of size 3\n        return 0;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[2, 5, 1, 7, 3]], "expected": 13},
                {"input": [[4, 4]], "expected": 8},
                {"input": [[9, 1, 1]], "expected": 11},
            ],
        },
    ],
    "Cybersecurity Analyst": [
        {
            "id": "cyber_code_01",
            "type": "coding",
            "sub_topic": "Secrets Management",
            "text": "Write a function that masks a token by replacing every character except the last 4 with '*'.",
            "function_name": "mask_token",
            "param_types": ["String"],
            "return_type": "String",
            "starter_code": {
                "python": "def mask_token(token):\n    # keep only the last 4 characters visible\n    return ''\n",
                "java": "public class Solution {\n    public static String mask_token(String token) {\n        // keep only the last 4 characters visible\n        return \"\";\n    }\n}\n",
            },
            "test_cases": [
                {"input": ["abcdef1234"], "expected": "******1234"},
                {"input": ["1234"], "expected": "1234"},
                {"input": ["xy"], "expected": "xy"},
            ],
        },
        {
            "id": "cyber_code_02",
            "type": "coding",
            "sub_topic": "Incident Monitoring",
            "text": "Write a function that counts how many log events are exactly 'FAIL'.",
            "function_name": "count_failed_attempts",
            "param_types": ["String[]"],
            "return_type": "int",
            "starter_code": {
                "python": "def count_failed_attempts(events):\n    count = 0\n    for event in events:\n        # count FAIL events\n        pass\n    return count\n",
                "java": "public class Solution {\n    public static int count_failed_attempts(String[] events) {\n        int count = 0;\n        for (String event : events) {\n            // count FAIL events\n        }\n        return count;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [["FAIL", "PASS", "FAIL"]], "expected": 2},
                {"input": [["PASS"]], "expected": 0},
                {"input": [["FAIL", "FAIL"]], "expected": 2},
            ],
        },
        {
            "id": "cyber_code_03",
            "type": "coding",
            "sub_topic": "Password Policy",
            "text": "Write a function that returns true when the password length is at least 8 and it contains at least one digit.",
            "function_name": "is_strong_password",
            "param_types": ["String"],
            "return_type": "boolean",
            "starter_code": {
                "python": "def is_strong_password(password):\n    # check minimum length and at least one digit\n    return False\n",
                "java": "public class Solution {\n    public static boolean is_strong_password(String password) {\n        // check minimum length and at least one digit\n        return false;\n    }\n}\n",
            },
            "test_cases": [
                {"input": ["secure123"], "expected": True},
                {"input": ["short"], "expected": False},
                {"input": ["longpassword"], "expected": False},
            ],
        },
    ],
    "UI/UX Designer": [
        {
            "id": "uiux_code_01",
            "type": "coding",
            "sub_topic": "Labels",
            "text": "Write a function that truncates the text to max_length characters. If truncation happens, append '...'.",
            "function_name": "truncate_label",
            "param_types": ["String", "int"],
            "return_type": "String",
            "starter_code": {
                "python": "def truncate_label(text, max_length):\n    # truncate text and append ... only when needed\n    return text\n",
                "java": "public class Solution {\n    public static String truncate_label(String text, int max_length) {\n        // truncate text and append ... only when needed\n        return text;\n    }\n}\n",
            },
            "test_cases": [
                {"input": ["Accessibility", 5], "expected": "Acces..."},
                {"input": ["UI", 5], "expected": "UI"},
                {"input": ["Design", 6], "expected": "Design"},
            ],
        },
        {
            "id": "uiux_code_02",
            "type": "coding",
            "sub_topic": "Accessibility",
            "text": "Write a function that counts how many button labels are non-empty after trimming spaces.",
            "function_name": "count_accessible_buttons",
            "param_types": ["String[]"],
            "return_type": "int",
            "starter_code": {
                "python": "def count_accessible_buttons(labels):\n    count = 0\n    for label in labels:\n        # count labels that are not empty after trimming\n        pass\n    return count\n",
                "java": "public class Solution {\n    public static int count_accessible_buttons(String[] labels) {\n        int count = 0;\n        for (String label : labels) {\n            // count labels that are not empty after trimming\n        }\n        return count;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [["Save", " ", "Cancel"]], "expected": 2},
                {"input": [["   ", ""]], "expected": 0},
                {"input": [["Submit"]], "expected": 1},
            ],
        },
        {
            "id": "uiux_code_03",
            "type": "coding",
            "sub_topic": "Spacing",
            "text": "Write a function that builds a 3-step spacing scale from the base value: [base, base * 2, base * 3].",
            "function_name": "build_spacing_scale",
            "param_types": ["int"],
            "return_type": "int[]",
            "starter_code": {
                "python": "def build_spacing_scale(base):\n    # return [base, base * 2, base * 3]\n    return []\n",
                "java": "public class Solution {\n    public static int[] build_spacing_scale(int base) {\n        // return [base, base * 2, base * 3]\n        return new int[]{};\n    }\n}\n",
            },
            "test_cases": [
                {"input": [8], "expected": [8, 16, 24]},
                {"input": [4], "expected": [4, 8, 12]},
                {"input": [1], "expected": [1, 2, 3]},
            ],
        },
    ],
    "Backend Developer": [
        {
            "id": "be_code_01",
            "type": "coding",
            "sub_topic": "Pagination",
            "text": "Write a function that returns the start index for pagination using page number and page size. Pages are 1-based.",
            "function_name": "paginate_start",
            "param_types": ["int", "int"],
            "return_type": "int",
            "starter_code": {
                "python": "def paginate_start(page, page_size):\n    # pages are 1-based\n    return 0\n",
                "java": "public class Solution {\n    public static int paginate_start(int page, int page_size) {\n        // pages are 1-based\n        return 0;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [1, 20], "expected": 0},
                {"input": [3, 10], "expected": 20},
                {"input": [2, 5], "expected": 5},
            ],
        },
        {
            "id": "be_code_02",
            "type": "coding",
            "sub_topic": "Caching",
            "text": "Write a function that counts how many cache result strings are exactly 'hit'.",
            "function_name": "count_cache_hits",
            "param_types": ["String[]"],
            "return_type": "int",
            "starter_code": {
                "python": "def count_cache_hits(results):\n    count = 0\n    for result in results:\n        # count cache hits\n        pass\n    return count\n",
                "java": "public class Solution {\n    public static int count_cache_hits(String[] results) {\n        int count = 0;\n        for (String result : results) {\n            // count cache hits\n        }\n        return count;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [["hit", "miss", "hit"]], "expected": 2},
                {"input": [["miss"]], "expected": 0},
                {"input": [["hit"]], "expected": 1},
            ],
        },
        {
            "id": "be_code_03",
            "type": "coding",
            "sub_topic": "Deduplication",
            "text": "Write a function that removes duplicate ids while preserving the first occurrence order.",
            "function_name": "unique_ids",
            "param_types": ["int[]"],
            "return_type": "int[]",
            "starter_code": {
                "python": "def unique_ids(ids):\n    seen = set()\n    result = []\n    # keep the first occurrence of each id\n    return result\n",
                "java": "import java.util.*;\npublic class Solution {\n    public static int[] unique_ids(int[] ids) {\n        HashSet<Integer> seen = new HashSet<>();\n        ArrayList<Integer> result = new ArrayList<>();\n        // keep the first occurrence of each id\n        int[] output = new int[result.size()];\n        for (int i = 0; i < result.size(); i++) {\n            output[i] = result.get(i);\n        }\n        return output;\n    }\n}\n",
            },
            "test_cases": [
                {"input": [[3, 1, 3, 2, 1]], "expected": [3, 1, 2]},
                {"input": [[7, 7]], "expected": [7]},
                {"input": [[]], "expected": []},
            ],
        },
    ],
}
