import React, { useState, useEffect, useRef } from 'react';

const STORAGE_KEY = 'careerbloom_history';

// ── Helpers ───────────────────────────────────────────────────────────────────
export function saveResult(domain, result) {
  const history = loadHistory();
  const entry = {
    id:           Date.now(),
    domain,
    quiz_score:   result.quiz_score   ?? 0,
    correct_count: result.correct_count ?? 0,
    total_questions: result.total_questions ?? 10,
    assessment_level: result.assessment_level ?? 'easy',
    readiness:    result.readiness?.readiness_score ?? 0,
    skill_match:  result.readiness?.skill_match     ?? 0,
    label:        result.readiness?.label           ?? '',
    weak_areas:   result.weak_areas   ?? [],
    timestamp:    new Date().toISOString(),
  };
  history.unshift(entry);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(history.slice(0, 20))); // keep last 20
}

export function loadHistory() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
  } catch {
    return [];
  }
}

function formatDate(iso) {
  const d = new Date(iso);
  return d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) +
    ' · ' + d.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
}

function scoreColor(score) {
  if (score >= 75) return { text: 'text-emerald-400', bg: 'bg-emerald-500', ring: 'ring-emerald-500/30' };
  if (score >= 45) return { text: 'text-amber-400',   bg: 'bg-amber-500',   ring: 'ring-amber-500/30' };
  return               { text: 'text-rose-400',    bg: 'bg-rose-500',    ring: 'ring-rose-500/30' };
}

function generateReportText(entry) {
  return [
    `NextStep — Assessment Report`,
    `================================`,
    `Domain:          ${entry.domain}`,
    `Date:            ${formatDate(entry.timestamp)}`,
    ``,
    `SCORES`,
    `------`,
    `Assessment Level: ${entry.assessment_level}`,
    `Quiz Score:      ${entry.quiz_score}%  (${entry.correct_count}/${entry.total_questions} correct)`,
    `Skill Match:     ${entry.skill_match}%`,
    `Overall Readiness: ${entry.readiness}%  [${entry.label}]`,
    ``,
    `WEAK AREAS`,
    `----------`,
    entry.weak_areas.length
      ? entry.weak_areas.map((a) => `  • ${a}`).join('\n')
      : '  None identified',
    ``,
    `Generated by NextStep AI`,
  ].join('\n');
}

function downloadReport(entry) {
  const text = generateReportText(entry);
  const blob = new Blob([text], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `careerbloom_${entry.domain.replace(/\W+/g, '_')}_${entry.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

function useInView(threshold = 0.1) {
  const ref = useRef(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) setVisible(true); }, { threshold });
    if (ref.current) obs.observe(ref.current);
    return () => obs.disconnect();
  }, [threshold]);
  return [ref, visible];
}

// ── Mini score ring (pure CSS) ────────────────────────────────────────────────
const ScoreRing = ({ value, size = 52 }) => {
  const c   = scoreColor(value);
  const r   = (size - 6) / 2;
  const circ = 2 * Math.PI * r;
  const offset = circ - (value / 100) * circ;
  return (
    <div className="relative shrink-0" style={{ width: size, height: size }}>
      <svg width={size} height={size} className="-rotate-90">
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth={6} />
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke="currentColor"
          strokeWidth={6} strokeLinecap="round"
          strokeDasharray={circ} strokeDashoffset={offset}
          className={`${c.text} transition-all duration-700`} />
      </svg>
      <div className="absolute inset-0 flex items-center justify-center">
        <span className={`text-[11px] font-bold ${c.text}`}>{value}%</span>
      </div>
    </div>
  );
};

// ── History row ───────────────────────────────────────────────────────────────
const HistoryRow = ({ entry, index, onRetest }) => {
  const c = scoreColor(entry.readiness);
  const [ref, visible] = useInView(0.05);

  return (
    <div
      ref={ref}
      style={{ transitionDelay: `${index * 50}ms` }}
      className={`flex items-center gap-4 rounded-2xl border border-white/[0.07] bg-slate-900/50 px-5 py-4
        transition-all duration-500 hover:border-white/[0.12] hover:bg-slate-900/70
        ${visible ? 'opacity-100 translate-x-0' : 'opacity-0 -translate-x-4'}`}
    >
      <ScoreRing value={entry.readiness} />

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <p className="text-sm font-semibold text-white truncate">{entry.domain}</p>
          <span className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold ring-1 ${c.ring} ${c.text} bg-transparent border-current`}>
            {entry.label}
          </span>
          <span className="rounded-full border border-slate-700 px-2 py-0.5 text-[10px] font-semibold text-slate-400">
            {entry.assessment_level}
          </span>
        </div>
        <p className="text-[11px] text-slate-500 mt-0.5">{formatDate(entry.timestamp)}</p>
        <div className="flex items-center gap-3 mt-1.5 text-[11px] text-slate-400">
          <span>Quiz: <span className="text-white font-medium">{entry.quiz_score}%</span></span>
          <span className="text-slate-700">·</span>
          <span>{entry.correct_count}/{entry.total_questions} correct</span>
          <span className="text-slate-700">·</span>
          <span>Skills: <span className="text-white font-medium">{entry.skill_match}%</span></span>
          {entry.weak_areas.length > 0 && (
            <>
              <span className="text-slate-700">·</span>
              <span className="text-rose-400 truncate max-w-[140px]">
                Weak: {entry.weak_areas.slice(0, 2).join(', ')}
              </span>
            </>
          )}
        </div>
      </div>

      <div className="flex items-center gap-2 shrink-0">
        <button
          onClick={() => onRetest(entry.domain)}
          className="rounded-xl border border-indigo-500/30 bg-indigo-500/10 px-3 py-1.5 text-[11px] font-semibold text-indigo-300 hover:bg-indigo-500/20 transition-colors"
        >
          Re-test
        </button>
        <button
          onClick={() => downloadReport(entry)}
          title="Download report"
          className="flex h-7 w-7 items-center justify-center rounded-xl border border-slate-700 text-slate-400 hover:border-slate-500 hover:text-white transition-colors"
        >
          <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
          </svg>
        </button>
      </div>
    </div>
  );
};

// ── Main ──────────────────────────────────────────────────────────────────────
const ResultsHistory = ({ onRetest }) => {
  const [history, setHistory] = useState([]);
  const [headRef, headVisible] = useInView(0.1);

  useEffect(() => {
    setHistory(loadHistory());
    // Refresh when localStorage changes (e.g. new result saved)
    const handler = () => setHistory(loadHistory());
    window.addEventListener('careerbloom_history_updated', handler);
    return () => window.removeEventListener('careerbloom_history_updated', handler);
  }, []);

  const clearHistory = () => {
    localStorage.removeItem(STORAGE_KEY);
    setHistory([]);
  };

  return (
    <section id="results" className="py-20">
      <div
        ref={headRef}
        className={`flex flex-col sm:flex-row sm:items-end sm:justify-between mb-10 gap-4 transition-all duration-700
          ${headVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`}
      >
        <div>
          <p className="section-label mb-3">Your history</p>
          <h2 className="text-3xl font-bold text-white sm:text-4xl">Results</h2>
          <p className="mt-2 text-slate-500 text-sm">
            {history.length > 0
              ? `${history.length} assessment${history.length > 1 ? 's' : ''} on record — stored locally in your browser.`
              : 'No assessments yet. Take a test to see your history here.'}
          </p>
        </div>
        {history.length > 0 && (
          <button
            onClick={clearHistory}
            className="self-start sm:self-auto text-xs text-slate-600 hover:text-rose-400 transition-colors"
          >
            Clear history
          </button>
        )}
      </div>

      {history.length === 0 ? (
        <div className="rounded-3xl border border-dashed border-slate-700/60 bg-slate-900/30 py-16 text-center">
          <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-800/60 border border-slate-700/50">
            <svg className="h-6 w-6 text-slate-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z" />
            </svg>
          </div>
          <p className="text-slate-500 text-sm">No results yet</p>
          <p className="text-slate-600 text-xs mt-1">Complete an assessment to see your score history here.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {history.map((entry, i) => (
            <HistoryRow key={entry.id} entry={entry} index={i} onRetest={onRetest} />
          ))}
        </div>
      )}
    </section>
  );
};

export default ResultsHistory;
