// Addition: static direct-link bank for the Practice feature.
// The config stays local so the UI can render company-wise coding questions without any API calls.

const QUESTION_LINKS = {
  'Two Sum': 'https://leetcode.com/problems/two-sum/',
  'Add Two Numbers': 'https://leetcode.com/problems/add-two-numbers/',
  'Longest Substring Without Repeating Characters': 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
  'Median of Two Sorted Arrays': 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
  'Longest Palindromic Substring': 'https://leetcode.com/problems/longest-palindromic-substring/',
  'Container With Most Water': 'https://leetcode.com/problems/container-with-most-water/',
  '3Sum': 'https://leetcode.com/problems/3sum/',
  'Letter Combinations of a Phone Number': 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
  'Group Anagrams': 'https://leetcode.com/problems/group-anagrams/',
  'Maximum Subarray': 'https://leetcode.com/problems/maximum-subarray/',
  'Merge Intervals': 'https://leetcode.com/problems/merge-intervals/',
  'Insert Interval': 'https://leetcode.com/problems/insert-interval/',
  'Spiral Matrix': 'https://leetcode.com/problems/spiral-matrix/',
  'Set Matrix Zeroes': 'https://leetcode.com/problems/set-matrix-zeroes/',
  'Valid Sudoku': 'https://leetcode.com/problems/valid-sudoku/',
  'Product of Array Except Self': 'https://leetcode.com/problems/product-of-array-except-self/',
  'Top K Frequent Elements': 'https://leetcode.com/problems/top-k-frequent-elements/',
  'Longest Consecutive Sequence': 'https://leetcode.com/problems/longest-consecutive-sequence/',
  'Subarray Sum Equals K': 'https://leetcode.com/problems/subarray-sum-equals-k/',
  'Best Time to Buy and Sell Stock': 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
  'Contains Duplicate': 'https://leetcode.com/problems/contains-duplicate/',
  'Valid Anagram': 'https://leetcode.com/problems/valid-anagram/',
  'Find All Anagrams in a String': 'https://leetcode.com/problems/find-all-anagrams-in-a-string/',
  'Minimum Window Substring': 'https://leetcode.com/problems/minimum-window-substring/',
  'Longest Repeating Character Replacement': 'https://leetcode.com/problems/longest-repeating-character-replacement/',
  'Valid Parentheses': 'https://leetcode.com/problems/valid-parentheses/',
  'Generate Parentheses': 'https://leetcode.com/problems/generate-parentheses/',
  'Min Stack': 'https://leetcode.com/problems/min-stack/',
  'Daily Temperatures': 'https://leetcode.com/problems/daily-temperatures/',
  'Evaluate Reverse Polish Notation': 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
  'Search in Rotated Sorted Array': 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
  'Find Minimum in Rotated Sorted Array': 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
  'Binary Search': 'https://leetcode.com/problems/binary-search/',
  'Find Peak Element': 'https://leetcode.com/problems/find-peak-element/',
  'Koko Eating Bananas': 'https://leetcode.com/problems/koko-eating-bananas/',
  'Time Based Key-Value Store': 'https://leetcode.com/problems/time-based-key-value-store/',
  'Merge Two Sorted Lists': 'https://leetcode.com/problems/merge-two-sorted-lists/',
  'Reverse Linked List': 'https://leetcode.com/problems/reverse-linked-list/',
  'Reorder List': 'https://leetcode.com/problems/reorder-list/',
  'Linked List Cycle': 'https://leetcode.com/problems/linked-list-cycle/',
  'Remove Nth Node From End of List': 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
  'Copy List with Random Pointer': 'https://leetcode.com/problems/copy-list-with-random-pointer/',
  'LRU Cache': 'https://leetcode.com/problems/lru-cache/',
  'Merge k Sorted Lists': 'https://leetcode.com/problems/merge-k-sorted-lists/',
  'Binary Tree Level Order Traversal': 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
  'Binary Tree Right Side View': 'https://leetcode.com/problems/binary-tree-right-side-view/',
  'Validate Binary Search Tree': 'https://leetcode.com/problems/validate-binary-search-tree/',
  'Kth Smallest Element in a BST': 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
  'Lowest Common Ancestor of a Binary Search Tree': 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
  'Binary Tree Maximum Path Sum': 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
  'Serialize and Deserialize Binary Tree': 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
  'Invert Binary Tree': 'https://leetcode.com/problems/invert-binary-tree/',
  'Diameter of Binary Tree': 'https://leetcode.com/problems/diameter-of-binary-tree/',
  'Same Tree': 'https://leetcode.com/problems/same-tree/',
  'Word Search': 'https://leetcode.com/problems/word-search/',
  'Number of Islands': 'https://leetcode.com/problems/number-of-islands/',
  'Clone Graph': 'https://leetcode.com/problems/clone-graph/',
  'Course Schedule': 'https://leetcode.com/problems/course-schedule/',
  'Pacific Atlantic Water Flow': 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
  'Rotting Oranges': 'https://leetcode.com/problems/rotting-oranges/',
  'Word Ladder': 'https://leetcode.com/problems/word-ladder/',
  'Combination Sum': 'https://leetcode.com/problems/combination-sum/',
  'Permutations': 'https://leetcode.com/problems/permutations/',
  'Jump Game': 'https://leetcode.com/problems/jump-game/',
  'House Robber': 'https://leetcode.com/problems/house-robber/',
  'House Robber II': 'https://leetcode.com/problems/house-robber-ii/',
  'Coin Change': 'https://leetcode.com/problems/coin-change/',
  'Decode Ways': 'https://leetcode.com/problems/decode-ways/',
  'Longest Increasing Subsequence': 'https://leetcode.com/problems/longest-increasing-subsequence/',
  'Partition Equal Subset Sum': 'https://leetcode.com/problems/partition-equal-subset-sum/',
  'Unique Paths': 'https://leetcode.com/problems/unique-paths/',
  'Longest Common Subsequence': 'https://leetcode.com/problems/longest-common-subsequence/',
  'Edit Distance': 'https://leetcode.com/problems/edit-distance/',
  'Word Break': 'https://leetcode.com/problems/word-break/',
  'Find the Duplicate Number': 'https://leetcode.com/problems/find-the-duplicate-number/',
  'Task Scheduler': 'https://leetcode.com/problems/task-scheduler/',
  'Sliding Window Maximum': 'https://leetcode.com/problems/sliding-window-maximum/',
  'Network Delay Time': 'https://leetcode.com/problems/network-delay-time/',
  'Cheapest Flights Within K Stops': 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
  'Trapping Rain Water': 'https://leetcode.com/problems/trapping-rain-water/',
  'Find Median from Data Stream': 'https://leetcode.com/problems/find-median-from-data-stream/',
  'Palindromic Substrings': 'https://leetcode.com/problems/palindromic-substrings/',
  'Sort Colors': 'https://leetcode.com/problems/sort-colors/',
  'Target Sum': 'https://leetcode.com/problems/target-sum/',
};

// Addition: difficulty metadata extends the existing question objects without changing the config contract.
const QUESTION_DIFFICULTIES = {
  'Two Sum': 'Easy',
  'Add Two Numbers': 'Medium',
  'Longest Substring Without Repeating Characters': 'Medium',
  'Median of Two Sorted Arrays': 'Hard',
  'Longest Palindromic Substring': 'Medium',
  'Container With Most Water': 'Medium',
  '3Sum': 'Medium',
  'Letter Combinations of a Phone Number': 'Medium',
  'Group Anagrams': 'Medium',
  'Maximum Subarray': 'Medium',
  'Merge Intervals': 'Medium',
  'Insert Interval': 'Medium',
  'Spiral Matrix': 'Medium',
  'Set Matrix Zeroes': 'Medium',
  'Valid Sudoku': 'Medium',
  'Product of Array Except Self': 'Medium',
  'Top K Frequent Elements': 'Medium',
  'Longest Consecutive Sequence': 'Medium',
  'Subarray Sum Equals K': 'Medium',
  'Best Time to Buy and Sell Stock': 'Easy',
  'Contains Duplicate': 'Easy',
  'Valid Anagram': 'Easy',
  'Find All Anagrams in a String': 'Medium',
  'Minimum Window Substring': 'Hard',
  'Longest Repeating Character Replacement': 'Medium',
  'Valid Parentheses': 'Easy',
  'Generate Parentheses': 'Medium',
  'Min Stack': 'Medium',
  'Daily Temperatures': 'Medium',
  'Evaluate Reverse Polish Notation': 'Medium',
  'Search in Rotated Sorted Array': 'Medium',
  'Find Minimum in Rotated Sorted Array': 'Medium',
  'Binary Search': 'Easy',
  'Find Peak Element': 'Medium',
  'Koko Eating Bananas': 'Medium',
  'Time Based Key-Value Store': 'Medium',
  'Merge Two Sorted Lists': 'Easy',
  'Reverse Linked List': 'Easy',
  'Reorder List': 'Medium',
  'Linked List Cycle': 'Easy',
  'Remove Nth Node From End of List': 'Medium',
  'Copy List with Random Pointer': 'Medium',
  'LRU Cache': 'Medium',
  'Merge k Sorted Lists': 'Hard',
  'Binary Tree Level Order Traversal': 'Medium',
  'Binary Tree Right Side View': 'Medium',
  'Validate Binary Search Tree': 'Medium',
  'Kth Smallest Element in a BST': 'Medium',
  'Lowest Common Ancestor of a Binary Search Tree': 'Medium',
  'Binary Tree Maximum Path Sum': 'Hard',
  'Serialize and Deserialize Binary Tree': 'Hard',
  'Invert Binary Tree': 'Easy',
  'Diameter of Binary Tree': 'Easy',
  'Same Tree': 'Easy',
  'Word Search': 'Medium',
  'Number of Islands': 'Medium',
  'Clone Graph': 'Medium',
  'Course Schedule': 'Medium',
  'Pacific Atlantic Water Flow': 'Medium',
  'Rotting Oranges': 'Medium',
  'Word Ladder': 'Hard',
  'Combination Sum': 'Medium',
  'Permutations': 'Medium',
  'Jump Game': 'Medium',
  'House Robber': 'Medium',
  'House Robber II': 'Medium',
  'Coin Change': 'Medium',
  'Decode Ways': 'Medium',
  'Longest Increasing Subsequence': 'Medium',
  'Partition Equal Subset Sum': 'Medium',
  'Unique Paths': 'Medium',
  'Longest Common Subsequence': 'Medium',
  'Edit Distance': 'Hard',
  'Word Break': 'Medium',
  'Find the Duplicate Number': 'Medium',
  'Task Scheduler': 'Medium',
  'Sliding Window Maximum': 'Hard',
  'Network Delay Time': 'Medium',
  'Cheapest Flights Within K Stops': 'Medium',
  'Trapping Rain Water': 'Hard',
  'Find Median from Data Stream': 'Hard',
  'Palindromic Substrings': 'Medium',
  'Sort Colors': 'Medium',
  'Target Sum': 'Medium',
};

// Addition: reusable curated pools keep the company lists modular and easy to maintain.
const BIG_TECH_CORE = [
  'Two Sum',
  'Add Two Numbers',
  'Longest Substring Without Repeating Characters',
  'Group Anagrams',
  'Maximum Subarray',
  'Merge Intervals',
  'Product of Array Except Self',
  'Top K Frequent Elements',
  'Longest Consecutive Sequence',
  'Best Time to Buy and Sell Stock',
  'Valid Anagram',
  'Minimum Window Substring',
  'Longest Repeating Character Replacement',
  'Valid Parentheses',
  'LRU Cache',
  'Search in Rotated Sorted Array',
  'Binary Search',
  'Merge Two Sorted Lists',
  'Reverse Linked List',
  'Linked List Cycle',
  'Binary Tree Level Order Traversal',
  'Validate Binary Search Tree',
  'Kth Smallest Element in a BST',
  'Lowest Common Ancestor of a Binary Search Tree',
  'Word Search',
  'Number of Islands',
  'Clone Graph',
  'Course Schedule',
  'Rotting Oranges',
  'Combination Sum',
  'House Robber',
  'Coin Change',
  'Longest Increasing Subsequence',
  'Word Break',
  'Trapping Rain Water',
];

const SERVICE_CORE = [
  'Two Sum',
  'Longest Substring Without Repeating Characters',
  'Maximum Subarray',
  'Best Time to Buy and Sell Stock',
  'Contains Duplicate',
  'Valid Anagram',
  'Valid Parentheses',
  'Merge Two Sorted Lists',
  'Reverse Linked List',
  'Linked List Cycle',
  'Binary Search',
  'Search in Rotated Sorted Array',
  'Merge Intervals',
  'Product of Array Except Self',
  'Top K Frequent Elements',
  'Subarray Sum Equals K',
  'Binary Tree Level Order Traversal',
  'Validate Binary Search Tree',
  'Invert Binary Tree',
  'Same Tree',
  'Number of Islands',
  'Course Schedule',
  'Rotting Oranges',
  'Combination Sum',
  'House Robber',
  'Coin Change',
  'Longest Increasing Subsequence',
  'Unique Paths',
  'Word Break',
  'Find the Duplicate Number',
  'Sort Colors',
  'Task Scheduler',
  'Trapping Rain Water',
  'Find Peak Element',
  'Daily Temperatures',
];

// Addition: company-specific title lists are kept separate so the UI only consumes clean data.
const COMPANY_QUESTION_TITLES = {
  Google: [
    ...BIG_TECH_CORE,
    'Median of Two Sorted Arrays',
    'Longest Palindromic Substring',
    'Container With Most Water',
    '3Sum',
    'Insert Interval',
    'Serialize and Deserialize Binary Tree',
    'Pacific Atlantic Water Flow',
    'Word Ladder',
    'Permutations',
    'Decode Ways',
    'Partition Equal Subset Sum',
    'Longest Common Subsequence',
    'Edit Distance',
    'Sliding Window Maximum',
    'Find Median from Data Stream',
  ],
  Amazon: [
    ...BIG_TECH_CORE,
    'Subarray Sum Equals K',
    'Contains Duplicate',
    'Find All Anagrams in a String',
    'Daily Temperatures',
    'Find Minimum in Rotated Sorted Array',
    'Time Based Key-Value Store',
    'Reorder List',
    'Copy List with Random Pointer',
    'Binary Tree Right Side View',
    'Invert Binary Tree',
    'Diameter of Binary Tree',
    'Jump Game',
    'Unique Paths',
    'Target Sum',
    'Cheapest Flights Within K Stops',
  ],
  Microsoft: [
    ...BIG_TECH_CORE,
    'Longest Palindromic Substring',
    'Letter Combinations of a Phone Number',
    'Set Matrix Zeroes',
    'Valid Sudoku',
    'Evaluate Reverse Polish Notation',
    'Koko Eating Bananas',
    'Remove Nth Node From End of List',
    'Same Tree',
    'Binary Tree Maximum Path Sum',
    'Serialize and Deserialize Binary Tree',
    'Pacific Atlantic Water Flow',
    'Decode Ways',
    'Longest Common Subsequence',
    'Edit Distance',
    'Find the Duplicate Number',
  ],
  Meta: [
    ...BIG_TECH_CORE,
    'Container With Most Water',
    '3Sum',
    'Spiral Matrix',
    'Insert Interval',
    'Palindromic Substrings',
    'Generate Parentheses',
    'Daily Temperatures',
    'Binary Tree Right Side View',
    'Invert Binary Tree',
    'Diameter of Binary Tree',
    'Permutations',
    'Sliding Window Maximum',
    'Find Median from Data Stream',
    'Sort Colors',
    'Find Peak Element',
  ],
  Apple: [
    ...BIG_TECH_CORE,
    'Longest Palindromic Substring',
    'Letter Combinations of a Phone Number',
    'Spiral Matrix',
    'Set Matrix Zeroes',
    'Contains Duplicate',
    'Palindromic Substrings',
    'Binary Tree Maximum Path Sum',
    'Same Tree',
    'Diameter of Binary Tree',
    'Jump Game',
    'Decode Ways',
    'Unique Paths',
    'Longest Common Subsequence',
    'Find the Duplicate Number',
    'Sort Colors',
  ],
  Netflix: [
    ...BIG_TECH_CORE,
    '3Sum',
    'Subarray Sum Equals K',
    'Daily Temperatures',
    'Evaluate Reverse Polish Notation',
    'Find Peak Element',
    'Time Based Key-Value Store',
    'Reorder List',
    'Copy List with Random Pointer',
    'Serialize and Deserialize Binary Tree',
    'Pacific Atlantic Water Flow',
    'Network Delay Time',
    'Cheapest Flights Within K Stops',
    'Sliding Window Maximum',
    'Find Median from Data Stream',
    'Palindromic Substrings',
  ],
  TCS: [
    ...SERVICE_CORE,
    'Add Two Numbers',
    'Group Anagrams',
    'Longest Repeating Character Replacement',
    'Min Stack',
    'Remove Nth Node From End of List',
    'Binary Tree Right Side View',
    'Kth Smallest Element in a BST',
    'Jump Game',
    'Decode Ways',
    'Target Sum',
    'Set Matrix Zeroes',
    'Generate Parentheses',
    'Reorder List',
    'Diameter of Binary Tree',
    'Copy List with Random Pointer',
  ],
  Infosys: [
    ...SERVICE_CORE,
    'Longest Palindromic Substring',
    'Container With Most Water',
    'Find All Anagrams in a String',
    'Evaluate Reverse Polish Notation',
    'Find Minimum in Rotated Sorted Array',
    'Time Based Key-Value Store',
    'Copy List with Random Pointer',
    'Kth Smallest Element in a BST',
    'Lowest Common Ancestor of a Binary Search Tree',
    'Jump Game',
    'Partition Equal Subset Sum',
    'Longest Common Subsequence',
    'Edit Distance',
    'Permutations',
    'Palindromic Substrings',
  ],
  Wipro: [
    ...SERVICE_CORE,
    'Add Two Numbers',
    'Group Anagrams',
    'Minimum Window Substring',
    'Longest Repeating Character Replacement',
    'Min Stack',
    'Koko Eating Bananas',
    'Binary Tree Right Side View',
    'Diameter of Binary Tree',
    'Remove Nth Node From End of List',
    'Jump Game',
    'Decode Ways',
    'Generate Parentheses',
    'Set Matrix Zeroes',
    'Reorder List',
    'Sliding Window Maximum',
  ],
  Accenture: [
    ...SERVICE_CORE,
    'Longest Palindromic Substring',
    'Letter Combinations of a Phone Number',
    'Container With Most Water',
    'Insert Interval',
    'Evaluate Reverse Polish Notation',
    'Find Minimum in Rotated Sorted Array',
    'Kth Smallest Element in a BST',
    'Lowest Common Ancestor of a Binary Search Tree',
    'Serialize and Deserialize Binary Tree',
    'Binary Tree Maximum Path Sum',
    'Decode Ways',
    'Longest Common Subsequence',
    'Edit Distance',
    'Permutations',
    'Find Median from Data Stream',
  ],
};

// Addition: this helper guarantees direct-link objects and removes accidental duplicates inside a company list.
const buildQuestionList = (titles) => {
  const seen = new Set();

  return titles
    .filter((title) => {
      if (seen.has(title)) return false;
      seen.add(title);
      return true;
    })
    .map((title) => ({
      title,
      link: QUESTION_LINKS[title],
      // Addition: each question now carries a difficulty tag for frontend filtering.
      difficulty: QUESTION_DIFFICULTIES[title] || 'Medium',
    }))
    .filter((question) => question.link);
};

// Addition: shared HR interview prompts keep the new sections realistic and concise.
const BASE_HR_QUESTIONS = [
  'Tell me about yourself.',
  'Why do you want to join this company?',
  'Why are you interested in this role?',
  'What are your biggest strengths?',
  'What is one weakness you are working on?',
  'Describe a difficult challenge you handled.',
  'Tell me about a time you worked in a team.',
  'Describe a conflict you resolved at work or college.',
  'How do you handle pressure and deadlines?',
  'Tell me about a time you failed and what you learned.',
  'How do you prioritize your tasks?',
  'Describe a situation where you showed leadership.',
  'How do you handle feedback?',
  'Tell me about a time you learned something quickly.',
  'Why should we hire you?',
  'Where do you see yourself in five years?',
  'What motivates you at work?',
  'How do you adapt to change?',
  'Describe a time you took ownership of a problem.',
  'What kind of work environment helps you do your best?',
];

// Addition: company-specific HR prompts keep each company block distinct without changing the UI.
const COMPANY_HR_QUESTIONS = {
  Google: [
    'Why Google and not another big tech company?',
    'How do Google products influence your daily life?',
    'Tell me about a time you solved an ambiguous problem.',
    'How would you contribute to a high-impact Google team?',
    'What does innovation mean to you?',
  ],
  Amazon: [
    'Which Amazon leadership principle fits you best?',
    'Tell me about a time you disagreed and committed.',
    'Describe a situation where you earned customer trust.',
    'How have you shown ownership in a project?',
    'Tell me about a time you delivered results under pressure.',
  ],
  Microsoft: [
    'Why do you want to work at Microsoft?',
    'How do you build collaborative relationships in a team?',
    'Tell me about a time you supported someone else’s success.',
    'Describe a situation where you had to learn from feedback quickly.',
    'How would you contribute to Microsoft’s mission?',
  ],
  Meta: [
    'Why are you interested in Meta?',
    'Tell me about a fast-moving project you handled well.',
    'How do you balance speed and quality?',
    'Describe a time you used data to influence a decision.',
    'What excites you about building products at scale?',
  ],
  Apple: [
    'Why Apple?',
    'Tell me about a time you paid attention to detail.',
    'How do you balance craftsmanship and deadlines?',
    'Describe a project you improved through iteration.',
    'What does customer experience mean to you?',
  ],
  Netflix: [
    'Why Netflix?',
    'Tell me about a time you made a hard decision with limited guidance.',
    'How do you stay accountable in a high-performance environment?',
    'Describe a time you raised the quality bar.',
    'What does freedom with responsibility mean to you?',
  ],
  TCS: [
    'Why do you want to join TCS?',
    'How would you handle working with global clients?',
    'Tell me about a time you adapted to a process quickly.',
    'Describe a project where reliability mattered most.',
    'How do you maintain professionalism in client-facing work?',
  ],
  Infosys: [
    'Why Infosys?',
    'How would you handle a demanding client requirement?',
    'Tell me about a time you learned a new tool quickly.',
    'Describe a situation where process discipline helped you.',
    'What interests you about working in enterprise delivery?',
  ],
  Wipro: [
    'Why Wipro?',
    'How do you stay calm when supporting critical systems?',
    'Tell me about a time you improved operational efficiency.',
    'Describe a situation where you followed strict timelines.',
    'How would you handle frequent requirement changes?',
  ],
  Accenture: [
    'Why Accenture?',
    'How do you approach solving client business problems?',
    'Tell me about a time you communicated a technical idea clearly.',
    'Describe a project where teamwork was essential.',
    'How do you manage multiple stakeholders?',
  ],
};

// Addition: technical fundamentals stay short, commonly asked, and company-agnostic where appropriate.
const BASE_TECHNICAL_QUESTIONS = [
  'What is the time complexity of binary search?',
  'What is a hash map?',
  'What is the difference between stack and queue?',
  'What is the difference between array and linked list?',
  'What is recursion?',
  'What is dynamic programming?',
  'What is the difference between DFS and BFS?',
  'What is a binary search tree?',
  'What is normalization in DBMS?',
  'What is the difference between SQL and NoSQL?',
  'What is indexing in databases?',
  'What are the four pillars of OOP?',
  'What is polymorphism?',
  'What is the difference between process and thread?',
  'What is deadlock in operating systems?',
  'What is a race condition?',
  'What is caching?',
  'What is load balancing?',
  'What is an API?',
  'What is the difference between REST and GraphQL?',
];

// Addition: small company-specific technical prompts provide realistic flavor without affecting coding questions.
const COMPANY_TECHNICAL_QUESTIONS = {
  Google: [
    'How would you analyze the complexity of a search algorithm?',
    'What is the difference between heap and balanced tree?',
    'How would you design autocomplete at a high level?',
    'What is memoization and when would you use it?',
    'How do you detect cycles in a graph?',
  ],
  Amazon: [
    'How would you design a URL shortener at a high level?',
    'What is eventual consistency?',
    'How would you handle duplicate messages in a distributed system?',
    'What is the difference between horizontal and vertical scaling?',
    'How would you design an inventory service?',
  ],
  Microsoft: [
    'How would you explain virtual memory?',
    'What is the difference between interface and abstract class?',
    'How would you design a collaborative editor at a high level?',
    'What is a semaphore?',
    'How do you optimize a slow SQL query?',
  ],
  Meta: [
    'How would you design a news feed at a high level?',
    'What is sharding?',
    'How would you detect duplicate content efficiently?',
    'What is the tradeoff between latency and throughput?',
    'How would you design a real-time notification system?',
  ],
  Apple: [
    'How would you optimize an app for low memory usage?',
    'What is the difference between mutable and immutable objects?',
    'How would you design a simple sync service?',
    'What is an observer pattern?',
    'Why is thread safety important in client applications?',
  ],
  Netflix: [
    'How would you design a video streaming service at a high level?',
    'What is CDN caching?',
    'How do you improve resiliency in distributed systems?',
    'What is circuit breaking?',
    'How would you monitor service reliability?',
  ],
  TCS: [
    'What is ACID in databases?',
    'What is SDLC?',
    'How do you handle null pointer exceptions in code?',
    'What is exception handling?',
    'How would you explain client-server architecture?',
  ],
  Infosys: [
    'What is a primary key and foreign key?',
    'What is multithreading?',
    'How would you explain object-oriented design?',
    'What is the purpose of version control?',
    'How do you test an API?',
  ],
  Wipro: [
    'What is the difference between HTTP and HTTPS?',
    'What is a cron job?',
    'How would you debug a production issue?',
    'What is the purpose of logging?',
    'How do you monitor application health?',
  ],
  Accenture: [
    'How would you explain system design to a non-technical stakeholder?',
    'What is a microservice?',
    'What is message queuing?',
    'How do you secure an API?',
    'What is the difference between synchronous and asynchronous communication?',
  ],
};

// Addition: helper keeps HR/technical question text unique within each company list.
const buildTextQuestionList = (questions) => {
  const seen = new Set();
  return questions.filter((question) => {
    const normalized = question.trim();
    if (!normalized || seen.has(normalized)) return false;
    seen.add(normalized);
    return true;
  });
};

// Addition: exported structure now cleanly separates coding, HR, and technical interview preparation.
const companyQuestions = Object.entries(COMPANY_QUESTION_TITLES).map(([company, titles]) => ({
  company,
  codingQuestions: buildQuestionList(titles),
  hrQuestions: buildTextQuestionList([
    ...BASE_HR_QUESTIONS,
    ...(COMPANY_HR_QUESTIONS[company] || []),
  ]),
  technicalQuestions: buildTextQuestionList([
    ...BASE_TECHNICAL_QUESTIONS,
    ...(COMPANY_TECHNICAL_QUESTIONS[company] || []),
  ]),
}));

export default companyQuestions;
